language: python
python:
  - '2.7'
  - '3.3'
install: pip install -r requirements/testing.txt
before_script: mv config.py.template config.py
script: invoke test
services: redis-server
env: DUCHESS_ENV=Testing
after_success: coveralls
matrix:
  allow_failures:
    - python: '3.3'
