language: python
python:
  - '2.7'
  - '3.3'
install: pip install -r requirements/testing.txt
before_script:
  - mv config.py.template config.py
  - ./run.py
  - sleep 5
script:
  - nosetests
  - flake8 . --max-complexity 10
services:
  - redis-server
env: DUCHESS_ENV=Testing
matrix:
  allow_failures:
    - python: '3.3'
